### ISSUE TITLE
Sample not running on Safari

### ISSUE THREAD

**Issue by irineu** [minimalist-components/mn-dialog#1]
Safari: Version 9.0.3 (11601.4.4)
OSX: El Capitain 10.11.3 (15D21)

Throw this error at page load(http://codepen.io/darlanmendonca/full/JRGoxv)

```
[Error] Error while parsing the 'sandbox' attribute: 'allow-modals' is an invalid sandbox flag. (JRGoxv, line 239)

[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function)
```

Looks like my safari does not support the let, const and new ES keywords... Idk if it helps, but i've tried to declare `let x = "hello"` in my safari console and didn't worked, but on chrome have worked, so...

**Comment by darlanmendonca** [comment]
thanks @irineu I'm checking, in codepen I really forgot to enable babel transpile (es6 to es5)

I enabled in codepen now, probably works 
I will publish in a gh-page, is more easy to publish and dont forget anything :D

**Comment by darlanmendonca** [comment]
check out pls, https://minimalist-components.github.io/mn-dialog/
